# Generated by Django 4.0.3 on 2022-03-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
                ('order', models.SmallIntegerField(verbose_name='Order')),
                ('number_of_answers', models.SmallIntegerField(verbose_name='Number of answers')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='quiz.quiz', verbose_name='Quiz')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BooleanQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
                ('order', models.SmallIntegerField(verbose_name='Order')),
                ('is_true', models.BooleanField(verbose_name='Is true')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='quiz.quiz', verbose_name='Quiz')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
